In [6]:
import sys
sys.path.append('../../')

In [7]:
import pandas as pd

## 1. Chargement du jeu de donnée

In [8]:
df = pd.read_csv('../../data/outputs/05_merged_data.csv')

In [9]:
print(df.shape)
df.head()

(26080, 25)

,resultId,raceId,driverId,constructorId,grid,race_rank,points,laps,milliseconds,fastestLap,...,circuitId,circuit_name,constructor_name,country,constructor_is_active,code,nationality,driver_is_active,full_name,season_age
0,1,18,1,1,1,1,10.0,58,5690616,39,...,1,Australian Grand Prix,McLaren,British,1,HAM,British,1,Lewis Hamilton,23
1,2,18,2,2,5,2,8.0,58,5696094,41,...,1,Australian Grand Prix,BMW Sauber,German,0,HEI,German,0,Nick Heidfeld,31
2,3,18,3,3,7,3,6.0,58,5698779,41,...,1,Australian Grand Prix,Williams,British,1,ROS,German,0,Nico Rosberg,23
3,4,18,4,4,11,4,5.0,58,5707797,58,...,1,Australian Grand Prix,Renault,French,0,ALO,Spanish,1,Fernando Alonso,27
4,5,18,5,1,3,5,4.0,58,5708630,43,...,1,Australian Grand Prix,McLaren,British,1,KOV,Finnish,0,Heikki Kovalainen,27

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26080 entries, 0 to 26079
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   resultId               26080 non-null  int64
 1   raceId                 26080 non-null  int64
 2   driverId               26080 non-null  int64
 3   constructorId          26080 non-null  int64
 4   grid                   26080 non-null  int64
 5   race_rank              26080 non-null  int64
 6   points                 26080 non-null  float64
 7   laps                   26080 non-null  int64
 8   milliseconds           26080 non-null  int64
 9   fastestLap             26080 non-null  int64
 10  fastestLapTime         26080 non-null  int64
 11  fastestLapSpeed        26080 non-null  float64
 12  statusId               26080 non-null  int64
 13  year                   26080 non-null  int64
 14  round                  26080 non-null  int64
 15  circuitId              26080 non-null  int64
 16  circuit_name           26080 non-null  object
 17  constructor_name       26080 non-null  object
 18  country                26080 non-null  object
 19  constructor_is_active  26080 non-null  int64
 20  code                   26080 non-null  object
 21  nationality            26080 non-null  object
 22  driver_is_active       26080 non-null  int64
 23  full_name              26080 non-null  object
 24  season_age             26080 non-null  int64
dtypes: float64(2), int64(17), object(6)
memory usage: 5.0+ MB

## 2. Analyse de la distribution

In [11]:
df.describe()

,resultId,raceId,driverId,constructorId,grid,race_rank,points,laps,milliseconds,fastestLap,fastestLapTime,fastestLapSpeed,statusId,year,round,circuitId,constructor_is_active,driver_is_active,season_age
count,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000,2.608000e+04,26080.000000,2.608000e+04,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000,26080.000000
mean,13041.372661,536.695667,266.277569,49.059663,11.167561,12.854141,1.906635,46.076687,1.728964e+06,12.430023,3.849849e+06,59.377854,17.476074,1990.553144,8.368635,23.541488,0.316833,0.104256,29.937730
std,7530.008377,303.034639,272.581622,60.221056,7.232797,7.700068,4.219715,29.726058,2.922157e+06,21.365583,2.413925e+06,93.186184,26.129965,19.508665,4.949718,18.749739,0.465251,0.305598,5.283855
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000e+00,0.000000,5.540400e+04,0.000000,1.000000,1950.000000,1.000000,1.000000,0.000000,0.000000,18.000000
25%,6520.750000,294.750000,57.000000,6.000000,5.000000,6.000000,0.000000,22.000000,0.000000e+00,0.000000,1.047135e+05,0.000000,1.000000,1976.000000,4.000000,9.000000,0.000000,0.000000,26.000000
50%,13040.500000,519.000000,163.000000,25.000000,11.000000,12.000000,0.000000,53.000000,0.000000e+00,0.000000,5.400000e+06,0.000000,10.000000,1991.000000,8.000000,18.000000,0.000000,0.000000,29.000000
75%,19560.250000,791.000000,364.000000,58.250000,17.000000,18.000000,2.000000,66.000000,5.061896e+06,22.000000,5.400000e+06,185.559000,14.000000,2007.000000,12.000000,34.000000,1.000000,0.000000,33.000000
max,26085.000000,1110.000000,858.000000,214.000000,34.000000,39.000000,50.000000,200.000000,1.509054e+07,85.000000,5.400000e+06,257.320000,141.000000,2023.000000,22.000000,79.000000,1.000000,1.000000,59.000000